#!/usr/bin/env bash
# Not found page 404
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
URL="\\\trewrite ^/redirect_me https://github.com/Sebas15897 permanent;"
sudo sed -i "42i $URL" /etc/nginx/sites-available/default
sudo sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default
service nginx restart
