#!/usr/bin/env bash
# Install nginx web server with the following requirements:
# Listen on port 80
# Return a page that contains the string "Holberton School" on requests
# Configure nginx server to redirect /redirect_me to another page
# The redirection is a "301 Moved Permanently"
# Configure ngix server to have a custom 404 page
apt -y update
apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i 's/root \/var\/www\/html;/root \/var\/www\/html;\n\trewrite ^\/redirect_me http:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sed -i 's/root \/var\/www\/html;/root \/var\/www\/html;\n\terror_page 404 \/custom_404.html;/' /etc/nginx/sites-available/default
service nginx restart
