#!/usr/bin/env bash
# script that configures the container to fit the above requirements
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart